baseURL = 'https://omarkh.dev/'
languageCode = 'en-us'
title = "Omar's blog"
theme = 'mini'

[params]
copyright = " "
showPowerBy = false
author = "My self"
customCss = ["/css/custom.css"]
archive = "Blog"
links = [
    {"name"="Blog", "path"="/posts/"},
    {"name"="Tags", "path"="/tags/"},
    {"name"="Categories", "path"="/categories/"},
    {"name"="About", "path"="/about/"},
]
enableRSS = true

[permalinks]
[permalinks.section]
blog = "/posts/"
    
[markup.highlight]
style = "base16-snazzy"
